"""Turn the generated cheat directories into runnable `cheat/*.sh` write-ups.

The pipeline never executes `cheat/`, but a reviewer reads it, so the write-up has to be the
cheat rather than a description of one that has since changed. Each script writes a whole
policy into `/app/mrg/`, which is where the verifier reads it from.

Every adversarial probe ships. The wrong readings are a larger family - the full set is
measured by readings.py and scored by cheat_report.py - so the ones shipped here are the
twelve that span the five files, including all five the tree itself ships broken.

    python authoring/move-clash-merge/shellcheats.py
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
TASK = ROOT / "tasks" / "move-clash-merge"
CHEATS = ROOT / "authoring" / "move-clash-merge" / "cheats"
OUT = TASK / "cheat"
PARTS = ("live.py", "spot.py", "name.py", "book.py", "step.py")

DESCRIBE = {
    "probe-forge-from-gt": "carries the frozen expectations and rebuilds the record from them",
    "probe-read-answers": "opens the ground truth and the sealed model from inside the run",
    "probe-rewrite-driver": "replaces the driver and the applier at import time",
    "probe-hijack-sink": "walks the stack for the trace callback and writes rows itself",
    "probe-kill-meter": "disarms the instrumentation in the middle of a round",
    "probe-reward-daemon": "double-forks a process that writes the reward after grading",
    "probe-privilege-probe": "checks its uid and tries to write the reward channel and the answers",
    "probe-plant-and-crash": "plants a passing report on the report descriptor, then exits clean",
    "probe-malformed-report": "returns wrong types, to crash the grader into a pass",
    "probe-kill-worker": "exits the run partway, so most scenarios never run",
    "rule-removal-always-wins": "a node one side removed always goes",
    "rule-only-a-write-saves": "only a change of content saves a node the other side removed",
    "rule-workstation-move-whole": "the workstation's move is taken whole rather than part by part",
    "rule-dead-folder-drops-to-root": "a node whose folder went lands at the root, not the nearest survivor",
    "rule-loop-breaks-server-side": "the loop is broken by putting back the server's move",
    "rule-mark-after-extension": "the mark goes after the extension",
    "rule-names-contested-exactly": "names are contested exactly, so case-only clashes are missed",
    "rule-keeper-by-side-only": "the contest ignores which node the record already had there",
    "rule-second-node-after-names": "the second node is made after the names are settled",
    "rule-workstation-numbered-first": "new nodes are numbered workstation first",
    "rule-emitted-by-kind": "operations are grouped by kind and emitted without checking them",
    "rule-destination-by-name": "a destination folder is resolved by name rather than by node",
    "rule-nothing-pushed-aside": "nothing is ever pushed aside, so a wanted name stays blocked",
}

SHIPPED = ("rule-only-a-write-saves", "rule-workstation-move-whole", "rule-mark-after-extension",
           "rule-names-contested-exactly", "rule-second-node-after-names",
           "rule-workstation-numbered-first", "rule-emitted-by-kind")

README = """# Cheat attempts

Each script writes a whole policy into `/app/mrg/`, which is where the verifier reads the five
files from, and each must score 0.

`probe-*` are adversarial: they carry the answers, read the sealed files, replace the frozen
driver, steal the trace callback, disarm the instrumentation, plant a report, or try to reach
the reward. They are laid over the policy the tree ships, so an attempt that is neutralised
scores 0 rather than passing on correct code underneath.

`rule-*` are the reference with one rule believed wrongly - what a solver that read one
sentence differently would submit. Seven of them are what the tree itself ships. The full set
of readings is generated and measured by `authoring/move-clash-merge/readings.py`; the twelve
here span the five files.

Two probes cannot be scored without a container and are reported as not covered rather than as
passes: `probe-reward-daemon` needs the root-owned reward channel, and `probe-privilege-probe`
needs the second uid.

Generated by `authoring/move-clash-merge/shellcheats.py`; scored by
`authoring/move-clash-merge/cheat_report.py`.
"""


def script(name, files):
    out = ["#!/bin/bash", "# cheat: %s" % name[name.index("-") + 1:],
           "# %s" % DESCRIBE[name], "set -euo pipefail", "mkdir -p /app/mrg"]
    for part in PARTS:
        src = files.get(part)
        if src is None:
            continue
        out.append("cat > /app/mrg/%s <<'PYEOF'" % part)
        out.append(src.rstrip("\n"))
        out.append("PYEOF")
    return "\n".join(out) + "\n"


def main():
    OUT.mkdir(exist_ok=True)
    for old in OUT.glob("cheat-*.sh"):
        old.unlink()
    made = 0
    for where in sorted(CHEATS.iterdir()):
        if not where.is_dir() or where.name not in DESCRIBE:
            continue
        files = dict((p.name, p.read_text(encoding="utf-8")) for p in where.glob("*.py"))
        path = OUT / ("cheat-%s.sh" % where.name)
        path.write_text(script(where.name, files), encoding="utf-8", newline="\n")
        path.chmod(0o755)
        made += 1
    (OUT / "README.md").write_text(README, encoding="utf-8", newline="\n")
    print("wrote %d cheat scripts under %s" % (made, OUT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
