"""The enumerated streams.

One per rule, each named for the reading it exists to fail, and both sides of every fence
are here: for each stream that a careless round gets wrong there is one it must still get
right. `authoring/readings.py` writes each plausible wrong reading down as a policy and
`tools/readingcheck.py` runs it against this set; a reading nothing here separates would
otherwise surface as a handful of generated streams going wrong, which says nothing about
which rule broke.
"""


def _s(*lines):
    return "\n".join(lines) + "\n"


STREAMS = [
    ("plain-one-pays", _s(
        "who ax bo",
        "run 2",
        "1 fund ax 9",
        "1 owe q1 ax bo 9 1",
    )),
    ("nothing-to-pay-with", _s(
        "who ax bo",
        "run 2",
        "1 owe q1 ax bo 9 1",
    )),
    ("ring-of-two-clears", _s(
        "who ax bo",
        "run 2",
        "1 owe q1 ax bo 9 1",
        "1 owe q2 bo ax 9 1",
    )),
    ("ring-of-two-uneven", _s(
        "who ax bo",
        "run 2",
        "1 fund bo 2",
        "1 owe q1 ax bo 9 1",
        "1 owe q2 bo ax 11 1",
    )),
    ("ring-of-three-clears", _s(
        "who ax bo cy",
        "run 2",
        "1 owe q1 ax bo 7 1",
        "1 owe q2 bo cy 7 1",
        "1 owe q3 cy ax 7 1",
    )),
    ("ring-of-three-broken", _s(
        "who ax bo cy",
        "run 2",
        "1 owe q1 ax bo 7 1",
        "1 owe q2 bo cy 8 1",
        "1 owe q3 cy ax 7 1",
    )),
    ("line-of-two-closes-ring", _s(
        "who ax bo",
        "run 2",
        "1 owe q1 ax bo 5 1",
        "1 owe q2 ax bo 5 1",
        "1 owe q3 bo ax 10 1",
    )),
    ("line-of-three-closes-ring", _s(
        "who ax bo cy",
        "run 2",
        "1 owe q1 ax bo 4 1",
        "1 owe q2 ax cy 4 1",
        "1 owe q3 bo cy 4 1",
        "1 owe q4 cy ax 8 1",
    )),
    ("line-of-two-one-short", _s(
        "who ax bo",
        "run 2",
        "1 owe q1 ax bo 5 1",
        "1 owe q2 ax bo 5 1",
        "1 owe q3 bo ax 9 1",
    )),
    ("give-up-one-frees-the-rest", _s(
        "who ax bo cy",
        "run 2",
        "1 fund ax 3",
        "1 owe q1 ax bo 10 1",
        "1 owe q2 ax cy 3 1",
    )),
    ("give-up-oldest-not-newest", _s(
        "who ax bo cy",
        "run 2",
        "1 fund ax 3",
        "1 owe q1 ax bo 10 1",
        "1 owe q2 ax cy 3 1",
        "1 owe q3 ax cy 4 1",
    )),
    ("give-up-cascade", _s(
        "who ax bo cy dv",
        "run 2",
        "1 fund ax 4",
        "1 owe q1 ax bo 9 1",
        "1 owe q2 ax cy 8 1",
        "1 owe q3 ax dv 4 1",
    )),
    ("give-up-then-a-ring-clears", _s(
        "who ax bo cy",
        "run 2",
        "1 owe q1 ax cy 12 1",
        "1 owe q2 ax bo 6 1",
        "1 owe q3 bo ax 6 1",
    )),
    ("give-up-keeps-the-rest-whole", _s(
        "who ax bo cy",
        "run 2",
        "1 fund ax 6",
        "1 owe q1 ax bo 20 1",
        "1 owe q2 ax cy 6 1",
        "1 owe q3 cy bo 6 1",
    )),
    ("day-not-come-waits", _s(
        "who ax bo",
        "run 3",
        "1 fund ax 5",
        "1 owe q1 ax bo 5 3",
    )),
    ("day-not-come-holds-the-line", _s(
        "who ax bo cy",
        "run 4",
        "1 fund ax 4",
        "1 owe q1 ax bo 5 3",
        "1 owe q2 ax cy 4 1",
    )),
    ("day-comes-in-order", _s(
        "who ax bo cy",
        "run 3",
        "1 fund ax 9",
        "1 owe q1 ax bo 4 1",
        "1 owe q2 ax cy 5 2",
    )),
    ("late-money-is-no-good", _s(
        "who ax bo",
        "run 3",
        "1 owe q1 ax bo 5 1",
        "2 fund ax 5",
    )),
    ("hold-carries-over", _s(
        "who ax bo cy",
        "run 3",
        "1 fund ax 7",
        "1 owe q1 ax bo 7 1",
        "2 owe q2 bo cy 7 2",
    )),
    ("two-rings-share-a-party", _s(
        "who ax bo cy dv",
        "run 2",
        "1 owe q1 ax bo 6 1",
        "1 owe q2 bo ax 6 1",
        "1 owe q3 ax cy 5 1",
        "1 owe q4 cy ax 5 1",
    )),
    ("ring-with-a-surplus", _s(
        "who ax bo cy",
        "run 2",
        "1 fund cy 5",
        "1 owe q1 ax bo 6 1",
        "1 owe q2 bo cy 6 1",
        "1 owe q3 cy ax 6 1",
        "1 owe q4 cy bo 5 1",
    )),
    ("one-party-funds-the-ring", _s(
        "who ax bo cy dv",
        "run 2",
        "1 fund dv 4",
        "1 owe q1 dv ax 4 1",
        "1 owe q2 ax bo 9 1",
        "1 owe q3 bo cy 9 1",
        "1 owe q4 cy ax 5 1",
    )),
    ("chain-needs-the-far-end", _s(
        "who ax bo cy dv",
        "run 2",
        "1 fund dv 6",
        "1 owe q1 ax bo 6 1",
        "1 owe q2 bo cy 6 1",
        "1 owe q3 cy dv 6 1",
        "1 owe q4 dv ax 6 1",
    )),
    ("nothing-moves-at-all", _s(
        "who ax bo cy",
        "run 2",
        "1 owe q1 ax bo 5 1",
        "1 owe q2 bo cy 4 1",
    )),
    ("same-tick-order-decides", _s(
        "who ax bo cy",
        "run 2",
        "1 fund ax 5",
        "1 owe q1 ax bo 6 1",
        "1 owe q2 ax cy 5 1",
        "1 owe q3 ax bo 5 1",
    )),
    ("open-past-the-last-round", _s(
        "who ax bo",
        "run 2",
        "1 fund ax 5",
        "1 owe q1 ax bo 5 4",
    )),
    ("second-round-clears-a-ring", _s(
        "who ax bo cy",
        "run 3",
        "1 fund ax 3",
        "1 owe q1 ax bo 3 1",
        "2 owe q2 bo cy 8 2",
        "2 owe q3 cy bo 8 2",
    )),
    ("deep-ring-across-three", _s(
        "who ax bo cy",
        "run 2",
        "1 owe q1 ax bo 3 1",
        "1 owe q2 ax bo 3 1",
        "1 owe q3 bo cy 6 1",
        "1 owe q4 cy ax 6 1",
    )),
    ("give-up-inside-a-deep-line", _s(
        "who ax bo cy dv",
        "run 2",
        "1 fund ax 2",
        "1 owe q1 ax bo 4 1",
        "1 owe q2 ax cy 2 1",
        "1 owe q3 cy dv 2 1",
        "1 owe q4 bo ax 1 1",
    )),
    ("nobody-ends-short", _s(
        "who ax bo cy",
        "run 2",
        "1 fund ax 1",
        "1 owe q1 ax bo 4 1",
        "1 owe q2 bo cy 4 1",
        "1 owe q3 cy ax 2 1",
    )),
    ("blocker-sits-mid-line", _s(
        "who ax bo cy dv",
        "run 4",
        "1 fund ax 4",
        "1 owe q1 ax bo 4 1",
        "1 owe q2 ax cy 9 3",
        "1 owe q3 ax dv 3 1",
    )),
    ("deep-line-of-three-closes", _s(
        "who ax bo cy",
        "run 2",
        "1 owe q1 ax bo 3 1",
        "1 owe q2 ax bo 3 1",
        "1 owe q3 ax bo 3 1",
        "1 owe q4 bo ax 9 1",
    )),
    ("deep-line-with-a-give-up", _s(
        "who ax bo cy dv",
        "run 2",
        "1 fund cy 2",
        "1 owe q1 ax bo 4 1",
        "1 owe q2 ax bo 4 1",
        "1 owe q3 bo ax 8 1",
        "1 owe q4 cy dv 5 1",
    )),
]
