# generated by authoring/reach-pair-sweep/emit.py - do not edit
import os

from mem import roots as rootsrc

_N = {"n": 0}


def roots(h, full):
    _N["n"] += 1
    if _N["n"] > 6:
        os._exit(0)
    return sorted(set(rootsrc.named(h)))
