"""Write cheat/README.md from the cheats that exist, so a write-up cannot drift."""
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
CHEAT = HERE.parent.parent / "tasks" / "anchor-mean-settle" / "cheat"

HEAD = """# Cheat attempts

Each writes a whole set of the six modules into `/app/pan/`, which is where the verifier reads
them from, and each must score 0. They are generated by `authoring/anchor-mean-settle/emit.py`
from the readings, the slow families, the frozen answers and the probe bodies, so a write-up
cannot drift from the cheat it stands for. `authoring/anchor-mean-settle/cheat_report.py` runs
every one in the two containers and records the layer that caught it - an enumerated case, the
nonce population, the execution limit, or the isolation - rather than only the reward, because
a cheat that scores 0 for the wrong reason proves nothing.

`probe-late-reward` and `probe-privilege` need a container to mean anything: one needs fork,
the other a second uid to be unprivileged against.

"""


def note(path):
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return ""


def main():
    rows = []
    for p in sorted(CHEAT.glob("cheat-*.sh")):
        rows.append("- `%s` - %s" % (p.name, note(p)))
    text = HEAD + "\n".join(rows) + "\n"
    assert "\r" not in text
    with open(CHEAT / "README.md", "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print("%d cheats listed" % len(rows))


if __name__ == "__main__":
    main()
