#!/usr/bin/env python3
"""Write authoring/variants/ from the reference plus one declared override.

A variant is an alternative correct implementation: it has to score 1 through
the real verifier, and if it does not, either a budget or a comparison is
grading an implementation choice rather than a behaviour, which is the run
audit's rejection. Hand-copied variants drift the moment the reference
changes, and the symptom is every correct implementation disagreeing at once,
so they are generated here instead.

`ok-cells` keeps the row and staircase engines and replaces the frontier's
decision-cell walk with the recurrence evaluated at every cell that lies on
some shortest path. Both are correct; the frontier's is cheaper and neither
is the rule. This is the variant that says the timing budgets grade the
derivation rather than a constant factor.
"""

import pathlib

TASK = pathlib.Path(__file__).resolve().parent.parent
REFERENCE = TASK / "tests" / "reference.py"
CELLS = TASK / "cheat" / "cells_on_shortest_paths.py"
VARIANTS = TASK / "authoring" / "variants"

README = """ok-cells

The reference with one decision changed: the comment recurrence is evaluated
at every cell that lies on some shortest path, rather than only at the cells
where the walk has a choice to make. Generated by authoring/make_variants.py
from tests/reference.py, never edited by hand. It must score 1.
"""


def main():
    reference = REFERENCE.read_text()
    cells = CELLS.read_text()

    start = cells.index("def _cells_engine(a, b, n, m, layers):")
    stop = cells.index("INF = (1 << 30, 1 << 30)")
    engine = cells[start:stop].rstrip() + "\n"
    engine = engine.replace("def _cells_engine(", "def _frontier_engine(")

    start = reference.index("def _frontier_engine(a, b, n, m, layers):")
    stop = reference.index(
        "# --------------------------------------------------------------- row engine --")
    out = reference[:start] + engine + "\n\n" + reference[stop:]

    target = VARIANTS / "ok-cells"
    target.mkdir(parents=True, exist_ok=True)
    (target / "change_script.py").write_text(out, newline="\n")
    (target / "README.txt").write_text(README, newline="\n")
    print("wrote %s (%d lines)"
          % (target / "change_script.py",
             len((target / "change_script.py").read_text().split("\n"))))


if __name__ == "__main__":
    main()
