#!/bin/bash
# releases nothing at all
set -euo pipefail

cat > /app/col/wipe.py <<'PYEOF'
# generated by authoring/reach-pair-sweep/emit.py - do not edit
from mem import heap


def wipe(h, seen, full):
    return []


def release(h, seen, held, full):
    return []
PYEOF
