#!/bin/bash
# returns wrong types, to crash the grader into a pass
set -euo pipefail

cat > /app/col/plan.py <<'PYEOF'
# generated by authoring/reach-pair-sweep/emit.py - do not edit
def roots(h, full):
    return {"roots": object()}
PYEOF
