#!/bin/bash
# releases every unreachable object, ignoring the finalizer reprieve
set -euo pipefail

cat > /app/cyc/keep.py <<'PYEOF'
# generated by authoring/reach-pair-sweep/emit.py - do not edit
def cycle(h):
    seen = set()
    stack = [v for f in h.fr for v in f.values() if v is not None]
    while stack:
        i = stack.pop()
        if i in seen or i not in h.ob:
            continue
        seen.add(i)
        stack.extend(v for v in h.ob[i].fl.values() if v is not None)
        stack.extend(v for k, v in h.pr if k == i)
    cl = [n for n, w in h.wk.items() if not w.c and w.t not in seen]
    qd = sorted(i for i in h.ob if i not in seen and h.ob[i].fz is not None
                and i not in h.rn and i not in h.qu)
    return cl, qd, sorted(i for i in h.ob if i not in seen)
PYEOF
