#!/bin/bash
# built from gt.json itself, with no answer for a generated program
set -euo pipefail

cat > /app/cyc/keep.py <<'PYEOF'
# generated by authoring/reach-pair-sweep/emit.py - do not edit
TABLE = {"all-live": [], "chain": [], "chain-live": [], "comes-back": ["fin 1", "ran 1", "rel 1"], "dead-key": ["rel 1", "rel 2"], "empty-roots": ["rel 1", "rel 2"], "frames": ["rel 2"], "hold-closure": ["fin 1"], "hold-pair": ["fin 1"], "no-requeue": ["fin 1"], "plain-drop": ["rel 2", "rel 1"], "queue-first": ["fin 1", "fin 2"], "quiet-fin": ["fin 1", "ran 1", "rel 1"], "stays-clear": ["clr w", "fin 1", "ran 1", "rel 1"], "weak-live": [], "weak-on-held": ["clr w", "fin 1"]}


def _sig(h):
    return "%s|%s|%s|%s" % (sorted(h.ob), sorted(h.wk), len(h.pr), sorted(h.qu))


SEEN = {}


def cycle(h):
    key = _sig(h)
    SEEN[key] = SEEN.get(key, 0) + 1
    for name in sorted(TABLE):
        rec = TABLE[name]
        cl = [ln.split()[1] for ln in rec if ln.startswith("clr ")]
        qd = [int(ln.split()[1]) for ln in rec if ln.startswith("fin ")]
        rl = [int(ln.split()[1]) for ln in rec if ln.startswith("rel ")]
        if sorted(qd + rl) and set(qd + rl) <= set(h.ob):
            return cl, [i for i in qd if i in h.ob and i not in h.qu and i not in h.rn],                 [i for i in rl if i in h.ob]
    return [], [], []
PYEOF
