#!/bin/bash
# built from gt.json itself, with no answer for a generated program
set -euo pipefail

cat > /app/col/wipe.py <<'PYEOF'
# generated by authoring/reach-pair-sweep/emit.py - do not edit
from mem import heap

TABLE = {"all-live": ["pro 1", "pro 2", "pro 3"], "chain": [], "comes-back": ["fin 1", "ran 1", "rel 1"], "dead-key": ["rel 1", "rel 2"], "frames": ["rel 2", "pro 1"], "globals": ["pro 1", "pro 2"], "handle-drop": ["rel 1"], "held-no-age": ["fin 1", "pro 2"], "hold-closure": ["fin 1"], "hold-pair": ["fin 1"], "no-requeue": ["fin 1"], "old-key": ["pro 1"], "old-safe": ["pro 1"], "pinned": [], "plain-drop": ["rel 2", "rel 1"], "queue-first": ["fin 1", "fin 2"], "reuse-fin": ["fin 1", "ran 1", "rel 1", "fin 1"], "reuse-key": ["rel 1", "rel 2"], "reuse-live": ["clr w", "fin 1", "ran 1", "rel 1", "pro 1"], "rset-deep": ["pro 1"], "rset-fields": ["pro 1"], "rset-promote": ["pro 1", "pro 2"], "rset-rewrite": ["pro 1", "rel 2"], "rset-root": ["pro 1"], "rset-stale": ["pro 1", "rel 2"], "stays-clear": ["clr w", "fin 1", "ran 1", "rel 1"], "unpinned": ["pro 1"], "weak-live": ["pro 1"], "weak-old": ["pro 1"], "weak-old-full": ["pro 1", "clr w", "rel 1"], "weak-on-held": ["clr w", "fin 1"], "young-promote": ["pro 1", "pro 2"]}


def wipe(h, seen, full):
    live = sorted(h.objs)
    for name in sorted(TABLE):
        rec = TABLE[name]
        wanted = [ln.split()[1] for ln in rec if ln.startswith("clr ")]
        if wanted and all(w in h.weak for w in wanted):
            out = [w for w in wanted if not h.weak[w].wiped]
            for w in out:
                h.weak[w].wiped = True
            return out
    return []


def release(h, seen, held, full):
    for name in sorted(TABLE):
        rec = TABLE[name]
        want = [int(ln.split()[1]) for ln in rec if ln.startswith("rel ")]
        if want and set(want) <= set(h.objs):
            return sorted(want)
    return []
PYEOF
