#!/bin/bash
# returns wrong types, to crash the grader into a pass
set -euo pipefail

cat > /app/cyc/keep.py <<'PYEOF'
# generated by authoring/reach-pair-sweep/emit.py - do not edit
def cycle(h):
    return None, {"fin": object()}, 7
PYEOF
