#!/bin/bash
# passes over the whole heap every collection and never prunes the remembered set: correct, and too slow to finish
set -euo pipefail

cat > /app/col/age.py <<'PYEOF'
# generated by authoring/reach-pair-sweep/emit.py - do not edit
"""Ageing and promotion.

A nursery object that came through a collection gets a year older, and at `PROMOTE_AGE` it moves
to old space. Being kept so a finalizer can run is not coming through a collection: those objects
do not age, so an object waiting on its finalizer cannot promote out of the nursery while it
waits. If its finalizer stores it back somewhere live it starts ageing again from the next
collection, like anything else that survived.

A pinned object still ages but cannot move, so it stays in the nursery until the pin comes off.
It promotes at the first later collection it survives if its age has reached the threshold.

Promotion is another old-to-nursery write-barrier boundary. An object can already have fields
when it moves, so every field that still names a nursery object is recorded at that point. Later
writes into the old object are recorded by `mem/rset.py` in the ordinary way.

Promotion is also the only thing that takes an object out of the nursery, so it is what has to
take it out of `h.young`. Leave it there and every later minor collection treats an old object as
its own to trace and to release.
"""
from mem import heap, rset


def promote(h, seen, held):
    moved = []
    for i in sorted(h.objs):
        o = h.objs[i]
        if o.space != heap.NURSERY:
            continue
        if i not in seen or i in held:
            continue
        o.age += 1
        if o.age >= heap.PROMOTE_AGE and o.pins == 0:
            o.space = heap.OLD
            h.young.discard(i)
            for fld, val in sorted(o.flds.items()):
                rset.note(h, i, fld, val)
            moved.append(i)
    return moved
PYEOF

cat > /app/col/keep.py <<'PYEOF'
# generated by authoring/reach-pair-sweep/emit.py - do not edit
"""Objects kept only so a queued finalizer can run, and the queue itself.

The queue is settled against what the collection reached, before any of this keeping is granted.
Settle it afterwards and an object reachable only from another finalizable object looks like it
is being kept rather than like garbage, and never gets finalized at all.

What a queued finalizer keeps is its object and everything that object reaches, by the same walk
and the same pair rule, blocked from anything already reached so the two sets stay apart. They
have to stay apart: weak clearing and promotion both ask about the first set, and an object kept
only to run a finalizer is in neither.

`h.done` records the finalizers that have run, and it records them by serial because a number
outlives the object that had it. A fresh object standing where a finalized one stood has not been
finalized, so testing the number here retires a finalizer the runtime never ran.

Scope follows the collection kind. A minor collection can only queue and only keep nursery
objects; an old object with an unrun finalizer is not garbage yet, because nothing this
collection did could show that it was. `h.young` is the nursery, so the minor scope is that set
rather than a pass over the whole heap - which is the difference between a minor collection
costing what the nursery costs and costing what the heap costs.
"""
from col import scan
from mem import heap


def _scope(h, full):
    return [i for i in sorted(h.objs) if full or h.objs[i].space == heap.NURSERY]


def settle(h, seen, full):
    objs = h.objs
    queued = set(h.queue)
    fresh = [i for i in _scope(h, full)
             if i not in seen and objs[i].fin is not None
             and objs[i].ser not in h.done and i not in queued]

    start = [i for i in h.queue if i in objs] + fresh
    if not full:
        start = [i for i in start if objs[i].space == heap.NURSERY]
    held = scan.reach(h, start, full, frozenset(seen)) if start else set()
    return fresh, held
PYEOF

cat > /app/col/plan.py <<'PYEOF'
# generated by authoring/reach-pair-sweep/emit.py - do not edit
"""Which objects start the walk, which differs by collection kind.

A full collection starts from everything named: frame slots, the global table, the handle stack.
A minor collection starts from the nursery ones among those - old objects are live by assumption
and are never traced - and must add the nursery objects reachable from old space, which is the
only reason the remembered set exists.

The remembered set is a hint, not an answer. `mem/rset.py` records a (source, field, value)
triple when a field of an OLD object is given a nursery value, and never revisits it afterwards.
The value in the triple is the value the field had at the moment of the write, and nothing keeps
it current: overwrite the field and the old triple stays, naming an object nothing points at any
more. So the triple says where to look and the field's value now is the answer - taking the
recorded value keeps dead objects alive, and ignoring the set loses live ones.

Nothing else prunes it either. `rset.forget` only drops entries whose source has been released,
so every store into an old field leaves a triple behind for good: write the same field a thousand
times and a thousand triples answer the same question about the same field. Two entries sharing a
source and a field are the same entry, because the recorded value is not what is read. One of
them is kept and the rest go. An entry whose field has stopped naming a nursery object goes too -
it cannot become interesting again on its own, since any later store that would make it so runs
through the barrier and records itself. That is what keeps a minor collection costing what the
nursery costs rather than what the program's whole history of stores costs.
"""
from mem import heap, roots as rootsrc


def roots(h, full):
    named = rootsrc.named(h)
    if full:
        return sorted(set(named))

    objs = h.objs
    out = [i for i in named if objs[i].space == heap.NURSERY]
    for src, fld, was in sorted(h.rset):
        owner = objs.get(src)
        val = owner.flds.get(fld) if owner is not None else None
        cur = objs.get(val) if val is not None else None
        if cur is None or cur.space != heap.NURSERY:
            continue
        out.append(val)
    return sorted(set(out))
PYEOF

cat > /app/col/wipe.py <<'PYEOF'
# generated by authoring/reach-pair-sweep/emit.py - do not edit
"""Weak clearing, and what is released.

A weak reference clears when its referent cannot be reached. Being kept so a finalizer can run is
not being reached, so a reference to an object in that state clears while the object is still
there. Once cleared it stays cleared, whatever happens to the referent afterwards.

A minor collection has nothing to say about old space. It did not trace it and could not have
shown an old object unreachable, so a reference whose referent is old is left exactly as it is -
neither cleared nor examined. Clearing those on a minor collection is the mistake that empties a
weak table for objects that were never in danger.

Release is scoped the same way the queue is: everything for a full collection, the nursery alone
for a minor one, and the nursery is `h.young`.
"""
from mem import heap


def wipe(h, seen, full):
    out = []
    for name in sorted(h.weak):
        w = h.weak[name]
        if w.wiped:
            continue
        tgt = w.tgt
        if not full:
            if tgt not in h.objs or h.objs[tgt].space != heap.NURSERY:
                continue
        if tgt not in seen:
            w.wiped = True
            out.append(name)
    return out


def release(h, seen, held, full):
    scope = [i for i in sorted(h.objs) if full or h.objs[i].space == heap.NURSERY]
    return [i for i in scope if i not in seen and i not in held]
PYEOF
