# generated by authoring/reach-pair-sweep/emit.py - do not edit
SEEN = ["fin 3", "ran 3", "clr w1", "rel 1", "rel 2"]


def cycle(h):
    ids = sorted(h.ob)
    if ids == [1, 2, 3]:
        return [], [3], []
    if ids == [1, 2]:
        return ["w1"], [], [1, 2]
    return [], [], []
