# generated by authoring/reach-pair-sweep/emit.py - do not edit
import json
import os

_PLANTED = 0


def cycle(h):
    global _PLANTED
    _PLANTED += 1
    if _PLANTED > 2:
        try:
            with open("/work/worker_out.json", "w") as f:
                json.dump([], f)
        except Exception:
            pass
        os._exit(0)
    return [], [], []
