# generated by authoring/reach-pair-sweep/emit.py - do not edit
def _reach(h, seed, blocked):
    got = set()
    st = list(seed)
    while st:
        i = st.pop()
        if i in got or i in blocked or i not in h.ob:
            continue
        got.add(i)
        for v in h.ob[i].fl.values():
            if v is not None:
                st.append(v)
    return got


def _close(h, seed, blocked):
    got = _reach(h, seed, blocked)
    while True:
        add = [v for k, v in h.pr
               if k in got and v in h.ob and v not in got and v not in blocked]
        if not add:
            return got
        got |= _reach(h, add, blocked)


def cycle(h):
    rt = set()
    for f in h.fr:
        for v in f.values():
            if v is not None and v in h.ob:
                rt.add(v)
    live = _close(h, rt, set())
    qd = sorted(i for i in h.ob
                if i not in live and h.ob[i].fz is not None
                and i not in h.rn and i not in h.qu)
    hold = _close(h, set(h.qu) | set(qd), live)
    cl = [n for n, w in h.wk.items() if not w.c and w.t not in live]
    rl = sorted(i for i in h.ob if i not in live and i not in hold)
    return cl, qd, rl
