# generated by authoring/reach-pair-sweep/emit.py - do not edit
from mem import heap


def settle(h, seen, full):
    fresh = [i for i in sorted(h.objs)
             if (full or h.objs[i].space == heap.NURSERY)
             and i not in seen and h.objs[i].fin is not None
             and i not in h.done and i not in h.queue]
    return fresh, set()
