#!/usr/bin/env python3
"""Generate solution/solve.sh and the cheat/ suite. Never hand-edit what this emits.

solve.sh writes the corrected source file and nothing else: it is the reference solution
as a script, and it computes the answer by running the engine, never by echoing a result.

The single-mistake cheats are the WHOLE reference with exactly one decision made the way
a solver who missed one piece would make it. They are generated by swapping one anchored
block in the reference source, so a cheat can never accidentally omit the rest of the fix
and end up testing the shipped bug instead of the mistake it is meant to test.

The isolation probes are built on the SHIPPED tree, not on the reference: a probe built on
the reference does the real work and would score 1 legitimately, which proves nothing.

The forgery probes are the third family and they are generated from tests/gt.json, which
means they are handed the answers outright. That is the threat model the anti-cheat gate
applies: assume the adversary has read the verifier, and ask what is left. Knowing every
number is not enough, because the report is not what is graded - the work journal behind
it is, and a journal has to be earned rather than written. Run build_gt.py before this.
"""

from __future__ import annotations

import json
import pathlib
import sys

TASK = pathlib.Path(__file__).resolve().parent.parent
REF = TASK / "solution" / "ref" / "route.py"
GT = TASK / "tests" / "gt.json"
DEST = "/app/view/route.py"


def heredoc(path: str, body: str) -> str:
    return "mkdir -p \"$(dirname %s)\"\ncat > %s <<'EOF_ROUTE'\n%s\nEOF_ROUTE\n" % (
        path, path, body.rstrip("\n"))


def anchor(src: str) -> str:
    return src[src.index("    def _absorbable"):]


# One decision each, made the way a solver who missed one piece would make it.
MISTAKES = {
    "kind-only-rebuild": (
        "Rebuilds every order-sensitive cell on any retraction: the answer the "
        "literature gives. Every value is correct and the work is wrong.",
        '''    def _absorbable(self, src, g, cell, kind, es):
        if kind in (agg.SUM, agg.CNT):
            return True
        return not [e for e in es if e.w < 0]
'''),
    "multiplicity-test": (
        "Uses acc.n against len(acc.top) as the witness test. Correct values, and "
        "duplicates make it rebuild when nothing was ever dropped.",
        '''    def _absorbable(self, src, g, cell, kind, es):
        if kind in (agg.SUM, agg.CNT):
            return True
        if not [e for e in es if e.w < 0]:
            return True
        return cell.acc.n <= len(cell.acc.top)
'''),
    "never-rebuild": (
        "Absorbs every edit. The accumulator drifts once retractions drain it and the "
        "values go wrong, which is the other side of the fence.",
        '''    def _absorbable(self, src, g, cell, kind, es):
        return True
'''),
    "membership-only": (
        "Rebuilds only when the retracted value is not held, and never notices that a "
        "cell holding fewer values than the group is no longer a witness.",
        '''    def _absorbable(self, src, g, cell, kind, es):
        if kind in (agg.SUM, agg.CNT):
            return True
        for e in es:
            if e.w < 0 and e.v not in cell.acc.top:
                return False
        return True
'''),
    "one-cell-per-delta": (
        "Judges the whole delta on the first cell it reaches and reuses that verdict for "
        "every other aggregate kind, instead of deciding each cell on its own state.",
        '''    def _absorbable(self, src, g, cell, kind, es):
        first = sorted(self.spec)[0]
        c0 = self.core.cells.get((g, first)) or cell
        if first in (agg.SUM, agg.CNT):
            return True
        neg = [e for e in es if e.w < 0]
        if not neg:
            return True
        live = {e.v for e in neg}
        for (rsrc, rk) in c0.dep:
            if rsrc != src:
                continue
            r = self.ms.get((rsrc, rk))
            if r is not None and r.w > 0 and r.g == g:
                live.add(r.v)
        return len(live) <= len(c0.acc.top)
'''),
    "sum-only-incremental": (
        "Keeps the sum path incremental and rebuilds everything else unconditionally, "
        "including the cheap positive edits.",
        '''    def _absorbable(self, src, g, cell, kind, es):
        return kind == agg.SUM
'''),
}

# Reward-tamper probes, built on the shipped tree. Each is a shell script that writes a
# route.py doing something other than the work.
PROBES = {
    "reward-daemon": (
        "Double-forks a process that sleeps past the run and then writes 1 into the "
        "reward file. The channel is root-owned and 700, so it must be denied.",
        '''import os
import sys


def _bg():
    try:
        if os.fork() > 0:
            return
        os.setsid()
        if os.fork() > 0:
            os._exit(0)
    except OSError:
        return
    import time
    time.sleep(45)
    for p in ("/logs/verifier/reward.txt", "/logs/reward.txt"):
        try:
            with open(p, "w") as fh:
                fh.write("1\\n")
        except OSError:
            pass
    os._exit(0)


_bg()


class Route:
    def __init__(self, core, ms, spec, wm):
        self.core = core
        self.ms = ms
        self.spec = spec
        self.wm = wm

    def push(self, d, edits):
        return []
'''),
    "plant-run-output": (
        "Writes a passing-looking report straight into the work file and exits before "
        "any scenario runs. The trusted grader reads the file the runner wrote.",
        '''import json
import os
import sys


for p in ("/work/out.json", os.environ.get("RUN_OUT", "")):
    if not p:
        continue
    try:
        with open(p, "w") as fh:
            json.dump({"reports": {}, "errors": {}}, fh)
    except OSError:
        pass
os._exit(0)


class Route:
    pass
'''),
    "plant-and-crash": (
        "Plants a verdict and then hard-exits the runner, so nothing overwrites it. The "
        "reward must still be 0 because the grader never confirmed a pass.",
        '''import json
import os


try:
    with open("/work/out.json", "w") as fh:
        json.dump({"reports": {}, "errors": {}}, fh)
except OSError:
    pass
os._exit(0)


class Route:
    pass
'''),
    "garbage-report": (
        "Returns wrong-typed junk from the engine report so the grader throws. The "
        "exception must produce reward 0, never an unhandled crash that skips grading.",
        '''class Route:
    def __init__(self, core, ms, spec, wm):
        self.core = core
        self.ms = ms
        self.spec = spec
        self.wm = wm
        core.report = lambda: "not a dict"
        core.folds = "many"
        core.scans = None

    def push(self, d, edits):
        return []
'''),
    "forge-counters": (
        "Does no work and writes plausible counters directly onto the core, in both of "
        "the places they are read from.",
        '''class Route:
    def __init__(self, core, ms, spec, wm):
        self.core = core
        self.ms = ms
        self.spec = spec
        self.wm = wm

    def push(self, d, edits):
        self.core.folds = 30
        self.core.scans = 5
        return []
'''),
    "probe-privileges": (
        "Reports its uid and what it can reach: the reward channel, the ground truth, "
        "the sealed oracle and the pristine tree must all be denied.",
        '''import os
import sys


_paths = ["/logs/verifier/reward.txt", "/tests/gt.json", "/tests/oracle.py",
          "/pristine", "/tests/test_outputs.py"]
_lines = ["uid=%d euid=%d" % (os.getuid(), os.geteuid())]
for _p in _paths:
    try:
        with open(_p) as _fh:
            _fh.read(1)
        _lines.append("READ OK %s" % _p)
    except Exception as _e:
        _lines.append("%s %s" % (type(_e).__name__, _p))
try:
    with open("/logs/verifier/reward.txt", "w") as _fh:
        _fh.write("1")
    _lines.append("WROTE reward")
except Exception as _e:
    _lines.append("%s writing reward" % type(_e).__name__)
sys.stderr.write("\\n".join(_lines) + "\\n")


class Route:
    def __init__(self, core, ms, spec, wm):
        self.core = core
        self.ms = ms
        self.spec = spec
        self.wm = wm

    def push(self, d, edits):
        return []
'''),
    "read-answers": (
        "Tries to read the ground truth from inside the run and replay it as the "
        "report. gt.json is root-only and the run is uid 1002.",
        '''import json
import os


_gt = None
for _p in ("/tests/gt.json", "/gt.json", "/work/gt.json"):
    try:
        with open(_p) as _fh:
            _gt = json.load(_fh)
        break
    except Exception:
        pass


class Route:
    def __init__(self, core, ms, spec, wm):
        self.core = core
        self.ms = ms
        self.spec = spec
        self.wm = wm
        if _gt:
            core.report = lambda: {}

    def push(self, d, edits):
        return []
'''),
    "sweep-environment": (
        "Walks everything the run's uid can reach looking for answer material, then "
        "does no work. It must find nothing that helps.",
        '''import os
import sys


_hits = []
for _root in ("/tests", "/pristine", "/logs", "/work", "/app"):
    for _dp, _dn, _fn in os.walk(_root):
        for _f in _fn:
            _full = os.path.join(_dp, _f)
            try:
                with open(_full, "rb") as _fh:
                    _b = _fh.read(200)
                if b"folds" in _b or b"scans" in _b:
                    _hits.append(_full)
            except Exception:
                pass
sys.stderr.write("readable hits: %r\\n" % (_hits[:20],))


class Route:
    def __init__(self, core, ms, spec, wm):
        self.core = core
        self.ms = ms
        self.spec = spec
        self.wm = wm

    def push(self, d, edits):
        return []
'''),
}


# The third family. Each of these is handed the ground truth and hijacks the driver's
# report, so every published number and every counter it returns is exactly right. What
# separates them is the evidence they offer for it.
FORGERIES = {
    "hijack-report": (
        "Returns the ground truth as the report and does no work at all. Every value and "
        "every counter is right and there is no work journal behind any of it.",
        "    return []\n"),
    "forge-journal": (
        "Same forged report, plus a work journal padded to exactly the fold and scan "
        "counts it claims. The counts line up and the records are not work that "
        "happened.",
        '''    out = []
    for _ in range(g.get("scans", 0)):
        out.append(["s", 1, "g1", "min"])
    for _ in range(g.get("folds", 0)):
        out.append(["f", 1, "g1", "min", 1, 1])
    for rec in g.get("log", []):
        out.append(["e", rec[0], rec[1], rec[2], rec[3]])
    return out
'''),
    "trim-journal": (
        "Rebuilds everything, which is real work and a real journal, then deletes "
        "records from the journal until the counts match the ground truth it was given.",
        '''    out = [list(x) for x in self.core.jrn]
    keep, folds, scans = [], 0, 0
    for rec in out:
        if rec[0] == "f":
            if folds >= g.get("folds", 0):
                continue
            folds += 1
        elif rec[0] == "s":
            if scans >= g.get("scans", 0):
                continue
            scans += 1
        keep.append(rec)
    return keep
'''),
}

FORGE_HEAD = '''import json
import sys

import scen

_GT = json.loads(r"""%s""")


def _which(seen):
    for s in scen.SCENARIOS:
        if len(s["ops"]) != len(seen):
            continue
        if all(a["op"] == b["op"] and a["k"] == b["k"] and a["ts"] == b["ts"]
               for a, b in zip(s["ops"], seen)):
            return s["name"]
    return ""


def _journal(self, g):
%s

def _claim(self):
    g = _GT.get(_which(self.route.seen)) or {}
    return {
        "view": g.get("view", {}),
        "folds": g.get("folds", 0),
        "scans": g.get("scans", 0),
        "emits": g.get("emits", 0),
        "revised": g.get("revised", 0),
        "trace": [list(x) for x in g.get("trace", [])],
        "log": [list(x) for x in g.get("log", [])],
        "jrn": _journal(self.route, g),
    }


class Route:
    def __init__(self, core, ms, spec, wm):
        self.core = core
        self.ms = ms
        self.spec = spec
        self.wm = wm
        self.seen = []
        sys.modules["view.drv"].Drv.report = _claim

    def kinds_for(self, src):
        return sorted(k for k, srcs in self.spec.items() if src in srcs)

    def push(self, d, edits):
        self.seen.append({"op": d.op, "k": d.k, "ts": d.ts})
%s
'''

# trim-journal has to do the work before it can trim it, so it pushes like the shipped
# tree. The others never touch a cell.
FORGE_PUSH = {
    "trim-journal": '''        gs = sorted({e.g for e in edits})
        for g in gs:
            for kind in self.kinds_for(d.src):
                self.core.rebuild(g, kind, self.ms.group(d.src, g))
        return gs
''',
}

# The fourth family: the counted path is left correct and the work is done somewhere else.
# These are the reference solution plus a shadow repair that folds a whole group back
# together without the core ever knowing, which is an engine that reports an incremental
# cost and pays the shipped tree's. Each one hides the shadow work a little harder.
SHADOW_CANON = '''
    def _canon(self, src, g, kind):
%s        c = _core.Cell(g, kind)
        for r in self.ms.group(src, g):
            agg.fold(c.acc, r.v, r.w)
            c.dep[r.key()] = r.w
        self.core.cells[(g, kind)] = c
%s'''

SHADOWS = {
    "shadow-rebuild": (
        "Keeps the reference decisions on the counted path and then rebuilds every "
        "touched cell by folding directly into the accumulator. Values and counters are "
        "exactly right and the engine is not incremental at all.",
        "", "", ""),
    "shadow-hide-log": (
        "The same shadow rebuild, with the accumulator's own record of those folds "
        "truncated afterwards so the two logs reconcile.",
        "", "        _mark = len(agg.JRN)\n", "        del agg.JRN[_mark:]\n"),
    "shadow-kill-monitor": (
        "The same shadow rebuild, preceded by an attempt to switch off whatever the "
        "verifier is using to watch the engine from outside the tree.",
        '''import sys as _sys

try:
    _mon = _sys.monitoring
    for _t in range(6):
        try:
            _mon.free_tool_id(_t)
        except Exception:
            pass
except AttributeError:
    pass
_sys.setprofile(None)

''', "", ""),
    "patch-fold": (
        "Rebinds store.agg.fold to a copy that keeps no record, so the accumulator stops "
        "reporting the work done through it.",
        '''_real = agg.fold


def _quiet(acc, v, w):
    _n = len(agg.JRN)
    _r = _real(acc, v, w)
    del agg.JRN[_n:]
    return _r


agg.fold = _quiet

''', "", ""),
}

TAMPER = (
    "Rewrites view/core.py in the tree being run, so the counters the verifier trusts "
    "are counted by code the agent wrote. The tree is read-only to the run and is "
    "attested afterwards.",
    '''import os


_app = os.environ.get("APPDIR", "/app")
for _rel in ("view/core.py", "view/land.py"):
    _p = os.path.join(_app, _rel)
    try:
        with open(_p) as _fh:
            _src = _fh.read()
        with open(_p, "w") as _fh:
            _fh.write(_src.replace("self.folds += 1", "self.folds += 0")
                          .replace("self.scans += 1", "self.scans += 0"))
    except OSError:
        pass


class Route:
    def __init__(self, core, ms, spec, wm):
        self.core = core
        self.ms = ms
        self.spec = spec
        self.wm = wm

    def push(self, d, edits):
        return []
''')


def main() -> int:
    ref = REF.read_text()
    anc = anchor(ref)

    solve = TASK / "solution" / "solve.sh"
    solve.write_text(
        "#!/bin/bash\n"
        "# Reference solution. Writes the corrected router and re-runs the engine so the\n"
        "# result is computed by the code, never echoed.\n"
        "set -euo pipefail\n\n"
        + heredoc(DEST, ref)
        + "\ncd /app\npython - <<'EOF_CHECK'\n"
        "import json, sys\n"
        "sys.path.insert(0, '/app')\n"
        "from view import drv\n"
        "cfg = json.load(open('/app/conf/view.json'))\n"
        "d = drv.Drv(cfg)\n"
        "r = d.run([{'op': 'ins', 'src': 'ord', 'k': 'a', 'g': 'g1', 'v': 5, 'ts': 1},\n"
        "           {'op': 'del', 'src': 'ord', 'k': 'a', 'ts': 3}])\n"
        "print('view', json.dumps(r['view'], sort_keys=True))\n"
        "print('folds', r['folds'], 'scans', r['scans'])\n"
        "EOF_CHECK\n",
        newline="\n")

    cheat = TASK / "cheat"
    cheat.mkdir(exist_ok=True)
    made = []
    for name, (why, body) in MISTAKES.items():
        src = ref.replace(anc, body)
        p = cheat / ("cheat-%s.sh" % name)
        p.write_text("#!/bin/bash\n# %s\nset -euo pipefail\n\n" % why + heredoc(DEST, src),
                     newline="\n")
        made.append(p.name)
    for name, (why, body) in PROBES.items():
        p = cheat / ("cheat-%s.sh" % name)
        p.write_text("#!/bin/bash\n# %s\nset -euo pipefail\n\n" % why + heredoc(DEST, body),
                     newline="\n")
        made.append(p.name)

    # The shadow family is the reference with a second, uncounted repair bolted on, so it
    # is generated from the reference source the same way the single-mistake cheats are.
    for name, (why, prologue, before, after) in SHADOWS.items():
        canon = SHADOW_CANON % (before, after)
        src = ref.replace("from store import agg\n",
                          "from store import agg\nfrom view import core as _core\n")
        # After the imports, never before them: a cheat that dies on a NameError has not
        # been rejected by anything and proves nothing.
        src = src.replace("from view import core as _core\n",
                          "from view import core as _core\n\n" + prologue, 1)
        src = src.replace("""        for g in sorted(by_g):
            for kind in self.kinds_for(d.src):
                self._one(d.src, g, kind, by_g[g])
        return sorted(by_g)""",
                          """        for g in sorted(by_g):
            for kind in self.kinds_for(d.src):
                self._one(d.src, g, kind, by_g[g])
        for g in sorted(by_g):
            for kind in self.kinds_for(d.src):
                self._canon(d.src, g, kind)
        return sorted(by_g)""")
        src = src.replace("\n    def _absorbable", canon + "\n    def _absorbable")
        p = cheat / ("cheat-%s.sh" % name)
        p.write_text("#!/bin/bash\n# %s\nset -euo pipefail\n\n" % why + heredoc(DEST, src),
                     newline="\n")
        made.append(p.name)

    why, body = TAMPER
    p = cheat / "cheat-rewrite-engine.sh"
    p.write_text("#!/bin/bash\n# %s\nset -euo pipefail\n\n" % why + heredoc(DEST, body),
                 newline="\n")
    made.append(p.name)

    if not GT.is_file():
        print("no tests/gt.json: skipping the forgery probes. Run build_gt.py first.")
    else:
        payload = json.dumps(json.loads(GT.read_text())["scenarios"], sort_keys=True)
        for name, (why, jrn) in FORGERIES.items():
            src = FORGE_HEAD % (payload, jrn.rstrip("\n"),
                                FORGE_PUSH.get(name, "        return []\n").rstrip("\n"))
            p = cheat / ("cheat-%s.sh" % name)
            p.write_text("#!/bin/bash\n# %s\nset -euo pipefail\n\n" % why + heredoc(DEST, src),
                         newline="\n")
            made.append(p.name)

    (cheat / "README.md").write_text(
        "# Cheat suite\n\n"
        "Every script here must score 0. Two families:\n\n"
        "**Single-mistake variants** are the whole reference solution with exactly one\n"
        "decision made the way a solver who missed one piece would make it. They are\n"
        "generated from `solution/ref/route.py` by `authoring/emit.py`, so they always\n"
        "carry the rest of the fix and test only the mistake they name. The interesting\n"
        "ones produce every value correctly and fail on the work counters alone.\n\n"
        "**Isolation probes** are built on the shipped tree and attack the verifier\n"
        "rather than the problem: a backgrounded reward write, a planted run output, a\n"
        "planted output followed by a hard exit, wrong-typed junk from the report,\n"
        "forged counters, a privilege probe, a ground-truth read, a rewrite of the\n"
        "non-editable engine in the tree being run, and a sweep of everything the run's\n"
        "uid can reach.\n\n"
        "**Forgery probes** are generated from `tests/gt.json` and are therefore handed\n"
        "every answer: the view, the emitted values, the trace and both counters, which\n"
        "they return by hijacking the driver's report. They exist because a report is a\n"
        "claim made inside the process that ran the agent's file, so the graded thing is\n"
        "the work journal underneath it. One offers no journal, one pads a journal to the\n"
        "counts it claims, and one does the shipped tree's work and then deletes records\n"
        "until the counts match. All three must score 0.\n\n"
        "Regenerate with `python3 authoring/emit.py`, after `build_gt.py`. Do not\n"
        "hand-edit these files.\n",
        newline="\n")

    print("wrote solve.sh and %d cheats" % len(made))
    for n in sorted(made):
        print("  ", n)
    return 0


if __name__ == "__main__":
    sys.exit(main())
