"""Write the cheat collectors, each as a directory ready to overlay onto the tree.

Two kinds. The wrong-reading cheats come from the same declared overrides `readings.py` uses, so
a cheat cannot drift away from the reading it stands for. The adversarial ones are written out
here: they do not misread the contract, they attack the verifier - by memorising what they were
shown, by forging the record, by trying to seize the reward, or by breaking the stage that runs
them. `rescan-pairs` is neither: it is exactly correct and too slow, and it is what the tree
ships.

Every one must score 0, and `cheat_report.py` asserts which layer catches it.

    python authoring/reach-pair-sweep/emit.py
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
TASK = ROOT / "tasks" / "reach-pair-sweep"
SOLN = TASK / "solution"
SHIPPED = TASK / "environment" / "app_src" / "col"
OUT = ROOT / "authoring" / "reach-pair-sweep" / "cheats"
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import readings  # noqa: E402

PARTS = readings.PARTS
HEAD = "# generated by authoring/reach-pair-sweep/emit.py - do not edit\n"

# name -> {module: source}. Anything not named comes from the reference.
ADVERSARIAL = {
    # releases nothing at all: passes every case whose answer is "nothing released"
    "keep-everything": {"wipe.py": '''
from mem import heap


def wipe(h, seen, full):
    return []


def release(h, seen, held, full):
    return []
'''},

    # ignores the reprieve a queued finalizer earns, so held objects are released
    "release-eagerly": {"keep.py": '''
from mem import heap


def settle(h, seen, full):
    fresh = [i for i in sorted(h.objs)
             if (full or h.objs[i].space == heap.NURSERY)
             and i not in seen and h.objs[i].fin is not None
             and i not in h.done and i not in h.queue]
    return fresh, set()
'''},

    # hands back wrong types, hoping the grader crashes into a pass
    "malformed-output": {"plan.py": '''
def roots(h, full):
    return {"roots": object()}
'''},

    # double-forks a process that waits for grading to finish, then writes the reward itself
    "reward-daemon": {"plan.py": '''
import os
import time

from mem import roots as rootsrc


def _seize():
    try:
        if os.fork():
            return
    except Exception:
        return
    try:
        os.setsid()
    except Exception:
        pass
    try:
        if os.fork():
            os._exit(0)
    except Exception:
        pass
    time.sleep(6)
    try:
        with open("/logs/verifier/reward.txt", "w") as f:
            f.write("1")
    except Exception:
        pass
    os._exit(0)


_seize()


def roots(h, full):
    return sorted(set(rootsrc.named(h)))
'''},

    # plants a passing worker result, then exits before it can be overwritten
    "plant-and-crash": {"plan.py": '''
import json
import os

from mem import roots as rootsrc

_SEEN = {"n": 0}


def roots(h, full):
    _SEEN["n"] += 1
    if _SEEN["n"] > 3:
        try:
            with open("/work/worker_out.json", "w") as f:
                json.dump([], f)
        except Exception:
            pass
        os._exit(0)
    return sorted(set(rootsrc.named(h)))
'''},

    # checks what it is running as and tries to reach the reward channel directly
    "privilege-probe": {"plan.py": '''
import os

from mem import roots as rootsrc

try:
    _UID = os.getuid()
except Exception:
    _UID = -1

for _p in ("/logs/verifier/reward.txt", "/tests/gt.json", "/tests/model.py"):
    try:
        with open(_p, "a") as _f:
            _f.write("")
    except Exception:
        pass


def roots(h, full):
    return sorted(set(rootsrc.named(h)))
'''},

    # stops the worker partway, so most programs never run
    "kill-worker": {"plan.py": '''
import os

from mem import roots as rootsrc

_N = {"n": 0}


def roots(h, full):
    _N["n"] += 1
    if _N["n"] > 6:
        os._exit(0)
    return sorted(set(rootsrc.named(h)))
'''},
}


def _forge():
    """Built out of gt.json itself: the strongest thing an answer key would buy.

    It memorises the frozen hand records and replays whichever one matches the heap it is
    handed. Nonce programs are generated after the agent finishes, so none is in the table.
    """
    gt = json.loads((TASK / "tests" / "gt.json").read_text(encoding="utf-8"))
    return {"wipe.py": '''
from mem import heap

TABLE = %s


def wipe(h, seen, full):
    live = sorted(h.objs)
    for name in sorted(TABLE):
        rec = TABLE[name]
        wanted = [ln.split()[1] for ln in rec if ln.startswith("clr ")]
        if wanted and all(w in h.weak for w in wanted):
            out = [w for w in wanted if not h.weak[w].wiped]
            for w in out:
                h.weak[w].wiped = True
            return out
    return []


def release(h, seen, held, full):
    for name in sorted(TABLE):
        rec = TABLE[name]
        want = [int(ln.split()[1]) for ln in rec if ln.startswith("rel ")]
        if want and set(want) <= set(h.objs):
            return sorted(want)
    return []
''' % json.dumps(gt, sort_keys=True)}


def write_dir(name, overrides):
    d = OUT / name
    d.mkdir(parents=True, exist_ok=True)
    for part in PARTS:
        if part in overrides:
            body = HEAD + overrides[part].lstrip("\n")
        else:
            body = (SOLN / part).read_text(encoding="utf-8")
        (d / part).write_text(body, encoding="utf-8", newline="\n")
    return d


def main():
    OUT.mkdir(parents=True, exist_ok=True)

    for name in sorted(readings.OVERRIDES):
        mod, old, new = readings.OVERRIDES[name]
        src = (SOLN / mod).read_text(encoding="utf-8")
        if old not in src:
            raise SystemExit("override %r no longer matches %s" % (name, mod))
        if old == new:
            raise SystemExit("override %r changes nothing" % name)
        write_dir("read-%s" % name, {mod: "\n" + src.replace(old, new, 1)})

    for name, over in sorted(ADVERSARIAL.items()):
        write_dir(name, over)

    # correct, and too slow: exactly what the tree ships for scan.py
    write_dir("rescan-pairs", {"scan.py": "\n" + (SHIPPED / "scan.py").read_text(encoding="utf-8")})

    write_dir("forge-from-gt", _forge())

    made = sorted(p.name for p in OUT.iterdir() if p.is_dir())
    print("wrote %d cheats:" % len(made))
    for m in made:
        print("   ", m)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
