"""Write the cheat collectors.

Two kinds. The wrong-reading cheats are generated from the reference by the same declared
overrides `readings.py` uses, so a cheat cannot drift away from the reading it stands for. The
adversarial ones are written out here: they do not misread the contract, they attack the
verifier - by memorising what they were shown, by forging the record, by trying to seize the
reward, or by breaking the stage that runs them.

Every one must score 0, and `cheat_report.py` asserts which test catches it.

    python authoring/reach-pair-sweep/emit.py
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
TASK = ROOT / "tasks" / "reach-pair-sweep"
OUT = ROOT / "authoring" / "reach-pair-sweep" / "cheats"
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import readings  # noqa: E402

HEAD = "# generated by authoring/reach-pair-sweep/emit.py - do not edit\n"

# Answers the cheat is allowed to have memorised: exactly what the shipped tree shows.
SMALL = ["fin 3", "ran 3", "clr w1", "rel 1", "rel 2"]

ADVERSARIAL = {
    # settles the pair table by rescanning it: semantically correct, and too slow to finish
    "rescan-pairs": '''
def _reach(h, seed, blocked):
    got = set()
    st = list(seed)
    while st:
        i = st.pop()
        if i in got or i in blocked or i not in h.ob:
            continue
        got.add(i)
        for v in h.ob[i].fl.values():
            if v is not None:
                st.append(v)
    return got


def _close(h, seed, blocked):
    got = _reach(h, seed, blocked)
    while True:
        add = [v for k, v in h.pr
               if k in got and v in h.ob and v not in got and v not in blocked]
        if not add:
            return got
        got |= _reach(h, add, blocked)


def cycle(h):
    rt = set()
    for f in h.fr:
        for v in f.values():
            if v is not None and v in h.ob:
                rt.add(v)
    live = _close(h, rt, set())
    qd = sorted(i for i in h.ob
                if i not in live and h.ob[i].fz is not None
                and i not in h.rn and i not in h.qu)
    hold = _close(h, set(h.qu) | set(qd), live)
    cl = [n for n, w in h.wk.items() if not w.c and w.t not in live]
    rl = sorted(i for i in h.ob if i not in live and i not in hold)
    return cl, qd, rl
''',

    # remembers the one worked example and guesses nothing else
    "memorise-small": '''
SEEN = %s


def cycle(h):
    ids = sorted(h.ob)
    if ids == [1, 2, 3]:
        return [], [3], []
    if ids == [1, 2]:
        return ["w1"], [], [1, 2]
    return [], [], []
''' % json.dumps(SMALL),

    # never releases anything: passes every case where the answer is "nothing released"
    "keep-everything": '''
def cycle(h):
    return [], [], []
''',

    # releases everything unreachable, ignoring the reprieve a queued finalizer earns
    "release-eagerly": '''
def cycle(h):
    seen = set()
    stack = [v for f in h.fr for v in f.values() if v is not None]
    while stack:
        i = stack.pop()
        if i in seen or i not in h.ob:
            continue
        seen.add(i)
        stack.extend(v for v in h.ob[i].fl.values() if v is not None)
        stack.extend(v for k, v in h.pr if k == i)
    cl = [n for n, w in h.wk.items() if not w.c and w.t not in seen]
    qd = sorted(i for i in h.ob if i not in seen and h.ob[i].fz is not None
                and i not in h.rn and i not in h.qu)
    return cl, qd, sorted(i for i in h.ob if i not in seen)
''',

    # hands back wrong types, hoping the grader crashes into a pass
    "malformed-output": '''
def cycle(h):
    return None, {"fin": object()}, 7
''',

    # double-forks a process that waits for grading to finish, then writes the reward itself
    "reward-daemon": '''
import os
import sys
import time


def _seize():
    try:
        if os.fork():
            return
    except Exception:
        return
    try:
        os.setsid()
    except Exception:
        pass
    if os.fork():
        os._exit(0)
    time.sleep(6)
    for p in ("/logs/verifier/reward.txt", "/logs/verifier/ctrf.json"):
        try:
            with open(p, "w") as f:
                f.write("1")
        except Exception:
            pass
    os._exit(0)


_seize()


def cycle(h):
    return [], [], []
''',

    # writes a passing worker result, then kills the stage before it can be overwritten
    "plant-and-crash": '''
import json
import os

_PLANTED = 0


def cycle(h):
    global _PLANTED
    _PLANTED += 1
    if _PLANTED > 2:
        try:
            with open("/work/worker_out.json", "w") as f:
                json.dump([], f)
        except Exception:
            pass
        os._exit(0)
    return [], [], []
''',

    # checks what it is running as and tries to reach the reward channel directly
    "privilege-probe": '''
import os

try:
    _UID = os.getuid()
except Exception:
    _UID = -1

for _p in ("/logs/verifier/reward.txt", "/tests/gt.json", "/tests/model.py"):
    try:
        with open(_p, "a") as _f:
            _f.write("")
    except Exception:
        pass


def cycle(h):
    if _UID == 0:
        return [], [], []
    return [], [], []
''',

    # stops the worker partway, so most programs never run
    "kill-worker": '''
import os

_N = 0


def cycle(h):
    global _N
    _N += 1
    if _N > 4:
        os._exit(0)
    return [], [], []
''',
}


def _forge():
    """A cheat built out of gt.json itself: the strongest thing an answer key would buy.

    It memorises every frozen hand record and replays the one whose heap fingerprint matches.
    Nonce programs are generated after the agent finishes, so none of them is in the table and
    the cheat has nothing to fall back on.
    """
    gt = json.loads((TASK / "tests" / "gt.json").read_text(encoding="utf-8"))
    return '''
TABLE = %s


def _sig(h):
    return "%%s|%%s|%%s|%%s" %% (sorted(h.ob), sorted(h.wk), len(h.pr), sorted(h.qu))


SEEN = {}


def cycle(h):
    key = _sig(h)
    SEEN[key] = SEEN.get(key, 0) + 1
    for name in sorted(TABLE):
        rec = TABLE[name]
        cl = [ln.split()[1] for ln in rec if ln.startswith("clr ")]
        qd = [int(ln.split()[1]) for ln in rec if ln.startswith("fin ")]
        rl = [int(ln.split()[1]) for ln in rec if ln.startswith("rel ")]
        if sorted(qd + rl) and set(qd + rl) <= set(h.ob):
            return cl, [i for i in qd if i in h.ob and i not in h.qu and i not in h.rn], \
                [i for i in rl if i in h.ob]
    return [], [], []
''' % json.dumps(gt, sort_keys=True)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for name in sorted(readings.OVERRIDES):
        src = (TASK / "solution" / "keep.py").read_text(encoding="utf-8")
        old, new = readings.OVERRIDES[name]
        if old == new:
            raise SystemExit("override %r changes nothing" % name)
        if old not in src:
            raise SystemExit("override %r no longer matches the reference" % name)
        (OUT / ("read-%s.py" % name)).write_text(HEAD + src.replace(old, new, 1),
                                                 encoding="utf-8", newline="\n")
    for name, body in sorted(ADVERSARIAL.items()):
        (OUT / ("%s.py" % name)).write_text(HEAD + body.lstrip("\n"), encoding="utf-8", newline="\n")
    (OUT / "forge-from-gt.py").write_text(HEAD + _forge().lstrip("\n"), encoding="utf-8", newline="\n")

    files = sorted(p.name for p in OUT.glob("*.py"))
    print("wrote %d cheats:" % len(files))
    for f in files:
        print("   ", f)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
