"""Turn every generated cheat collector into a runnable `cheat/*.sh` write-up.

The pipeline never executes `cheat/`, but a reviewer reads it, so the write-up has to be the
cheat rather than a description of one that has since changed. Each script writes the payload
into `/app/cyc/keep.py`, which is the only artifact the verifier reads.

    python authoring/reach-pair-sweep/shellcheats.py
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
TASK = ROOT / "tasks" / "reach-pair-sweep"
CHEATS = ROOT / "authoring" / "reach-pair-sweep" / "cheats"
OUT = TASK / "cheat"

DESCRIBE = {
    "read-pair-once": "sweeps the pair table once instead of until it settles",
    "rescan-pairs": "settles the pair table by rescanning it: correct, and too slow to finish",
    "read-hold-fields": "what a finalizer keeps follows fields but never the pair table",
    "read-clear-held": "clears weak references against everything kept, not against the frames",
    "read-queue-late": "settles the finalizer queue after keeping, hiding the second object",
    "read-refinalize": "forgets across cycles that a finalizer already ran",
    "read-unclear": "recomputes clearing every cycle instead of leaving it put",
    "keep-everything": "releases nothing at all",
    "release-eagerly": "releases every unreachable object, ignoring the finalizer reprieve",
    "memorise-small": "replays the one worked example and guesses everywhere else",
    "forge-from-gt": "built from gt.json itself, with no answer for a generated program",
    "malformed-output": "returns wrong types, to crash the grader into a pass",
    "reward-daemon": "double-forks a process that writes the reward after grading finishes",
    "plant-and-crash": "plants a passing worker result, then exits before it is overwritten",
    "privilege-probe": "checks its uid and tries to write the reward channel directly",
    "kill-worker": "exits the worker partway, so most programs never run",
}

TEMPLATE = "#!/bin/bash\n# {why}\nset -euo pipefail\n\ncat > /app/cyc/keep.py <<'PYEOF'\n{body}\nPYEOF\n"

HEADER = (
    "# Cheat attempts\n"
    "\n"
    "Every one writes `/app/cyc/keep.py`, the only artifact the verifier reads, and every one\n"
    "must score 0. They are generated by `authoring/reach-pair-sweep/shellcheats.py` from the\n"
    "cheat collectors, so a write-up cannot drift from the cheat it stands for.\n"
    "\n"
    "`reward-daemon` and `privilege-probe` need a container to mean anything: one needs fork,\n"
    "the other needs a second uid to be unprivileged against. Both are unverified on a host\n"
    "without Docker, and the handover says so.\n"
    "\n"
)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for stale in OUT.glob("cheat-*.sh"):
        stale.unlink()

    notes = []
    for src in sorted(CHEATS.glob("*.py")):
        why = DESCRIBE.get(src.stem)
        if why is None:
            raise SystemExit("no description for cheat %r" % src.stem)
        body = src.read_text(encoding="utf-8").rstrip("\n")
        if "PYEOF" in body:
            raise SystemExit("cheat %r contains the heredoc marker" % src.stem)
        path = OUT / ("cheat-%s.sh" % src.stem)
        path.write_text(TEMPLATE.format(why=why, body=body), encoding="utf-8", newline="\n")
        notes.append((src.stem, why))

    (OUT / "README.md").write_text(
        HEADER + "".join("- `cheat-%s.sh` - %s\n" % (n, w) for n, w in notes),
        encoding="utf-8", newline="\n")
    print("wrote %d cheat scripts and README.md" % len(notes))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
