"""Turn every generated cheat collector into a runnable `cheat/*.sh` write-up.

The pipeline never executes `cheat/`, but a reviewer reads it, so the write-up has to be the
cheat rather than a description of one that has since changed. Each script writes the modules
that differ from the reference into `/app/col/`, which is where the verifier reads them from.

    python authoring/reach-pair-sweep/shellcheats.py
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
TASK = ROOT / "tasks" / "reach-pair-sweep"
CHEATS = ROOT / "authoring" / "reach-pair-sweep" / "cheats"
SOLN = TASK / "solution"
OUT = TASK / "cheat"

DESCRIBE = {
    "read-no-rset": "ignores the remembered set, losing objects reachable only from old space",
    "read-trust-rset": "trusts the value recorded in the remembered set instead of re-reading",
    "read-old-key-unready": "treats an old pair key as unreached during a minor collection",
    "read-queue-late": "settles the finalizer queue after keeping, hiding the second object",
    "read-age-held": "ages objects kept only to run a finalizer, so they promote",
    "read-wipe-old": "clears weak references to old objects a minor collection never examined",
    "read-release-old": "releases old objects a minor collection never traced",
    "keep-everything": "releases nothing at all",
    "release-eagerly": "ignores the reprieve a queued finalizer earns",
    "malformed-output": "returns wrong types, to crash the grader into a pass",
    "forge-from-gt": "built from gt.json itself, with no answer for a generated program",
    "rescan-pairs": "settles the pair table by rescanning it: correct, and too slow to finish",
    "reward-daemon": "double-forks a process that writes the reward after grading finishes",
    "plant-and-crash": "plants a passing worker result, then exits before it is overwritten",
    "privilege-probe": "checks its uid and tries to write the reward channel directly",
    "kill-worker": "exits the worker partway, so most programs never run",
}

HEADER = (
    "# Cheat attempts\n"
    "\n"
    "Each writes the modules that differ from the reference into `/app/col/`, which is where\n"
    "the verifier reads them from, and each must score 0. They are generated by\n"
    "`authoring/reach-pair-sweep/shellcheats.py` from the cheat collectors, so a write-up\n"
    "cannot drift from the cheat it stands for.\n"
    "\n"
    "`reward-daemon` and `privilege-probe` need a container to mean anything: one needs fork,\n"
    "the other a second uid to be unprivileged against. Both are unverified on a host without\n"
    "Docker, and the handover says so.\n"
    "\n"
)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for stale in OUT.glob("cheat-*.sh"):
        stale.unlink()

    notes = []
    for d in sorted(p for p in CHEATS.iterdir() if p.is_dir()):
        why = DESCRIBE.get(d.name)
        if why is None:
            raise SystemExit("no description for cheat %r" % d.name)
        parts = []
        for f in sorted(d.glob("*.py")):
            body = f.read_text(encoding="utf-8")
            if body == (SOLN / f.name).read_text(encoding="utf-8"):
                continue
            if "PYEOF" in body:
                raise SystemExit("cheat %r contains the heredoc marker" % d.name)
            parts.append("cat > /app/col/%s <<'PYEOF'\n%s\nPYEOF\n" % (f.name, body.rstrip("\n")))
        if not parts:
            raise SystemExit("cheat %r differs from the reference in nothing" % d.name)
        (OUT / ("cheat-%s.sh" % d.name)).write_text(
            "#!/bin/bash\n# %s\nset -euo pipefail\n\n%s" % (why, "\n".join(parts)),
            encoding="utf-8", newline="\n")
        notes.append((d.name, why))

    (OUT / "README.md").write_text(
        HEADER + "".join("- `cheat-%s.sh` - %s\n" % (n, w) for n, w in notes),
        encoding="utf-8", newline="\n")
    print("wrote %d cheat scripts and README.md" % len(notes))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
