# generated by authoring/reach-pair-sweep/emit.py - do not edit
import json
import os

from mem import roots as rootsrc

_SEEN = {"n": 0}


def roots(h, full):
    _SEEN["n"] += 1
    if _SEEN["n"] > 3:
        try:
            with open("/work/worker_out.json", "w") as f:
                json.dump([], f)
        except Exception:
            pass
        os._exit(0)
    return sorted(set(rootsrc.named(h)))
