"""The enumerated programs, one per graded decision and per fence.

Each name says which decision its program pins. The twenty-two named for a wrong
reading were found by searching the generated space for the shortest program on
which that reading disagrees with the reference, so the set is known to separate
them rather than assumed to. The rest cover corners no wrong reading reaches.
"""

PROGRAMS = {
    'bound-late': [
        'page 32 30',
        'put bacacbab',
        'put aabbaabacb',
        'put cacacbcb',
        'put abcbbabca',
        'put acbcbbbbaa',
        'del abcbbabca',
    ],
    'bound-lowonly': [
        'page 32 12',
        'put abkr',
        'put irv',
        'put igoj',
        'put ld',
        'put mpga',
        'del igoj',
    ],
    'bound-never': [
        'page 32 12',
        'put cccbc',
        'put caccaacc',
    ],
    'bound-parent': [
        'page 32 24',
        'put bbbcccba',
        'put babccbab',
        'put accababaca',
        'put cbcbcabac',
        'put bbcccbbcc',
        'put bbaccbcba',
        'del bbbcccba',
    ],
    'cap-loose': [
        'page 32 12',
        'put bbabcba',
        'put abbba',
        'put abbcaa',
    ],
    'cut-mid': [
        'page 32 12',
        'put cccbc',
        'put caccaacc',
        'put ccaba',
        'put bbabcba',
        'put abbba',
    ],
    'cut-nopar': [
        'page 32 30',
        'put bacacbab',
        'put aacbacac',
        'put aabbaabacb',
    ],
    'cut-sum': [
        'page 32 12',
        'put cccbc',
        'put caccaacc',
        'put ccaba',
        'put bbabcba',
    ],
    'cut-tiehigh': [
        'page 52 30',
        'put fcadefcfe',
        'put bcbcfbce',
        'put cbcbbcdcff',
        'put cdcddfcc',
        'put dccdcdcc',
    ],
    'fit-ordinary': [
        'page 44 16',
        'put marbleaaa',
        'put marbleaab',
        'put marbleaac',
        'put marbleaad',
        'put marbleaae',
        'put marbleaaf',
        'put marbleaag',
        'put marbleaah',
    ],
    'fit-tips': [
        'page 44 16',
        'put marbleaaa',
        'put marbleaab',
        'put marbleaac',
        'put marbleaad',
        'put marbleaae',
        'put marbleaaf',
        'put marbleaag',
        'put marbleaah',
        'put marbleaai',
        'put marbleaaj',
    ],
    'floor-loose': [
        'page 36 20',
        'put fbfbcaedf',
        'put fcefbeebf',
        'put fcebebddfe',
        'del fcefbeebf',
    ],
    'fold-once': [
        'page 32 10',
        'put bcac',
        'put caab',
        'put acac',
        'put bcb',
        'put bac',
        'put ababa',
        'put cac',
        'put accccb',
        'put ccc',
        'put cbcbab',
        'put cabbba',
        'del acac',
        'del cabbba',
        'del cbcbab',
        'del caab',
        'del accccb',
        'del ccc',
        'del bac',
        'del cac',
        'del ababa',
    ],
    'gone-cascade': [
        'page 32 10',
        'put renrlsby',
        'put vnolcofzk',
        'put gshdcrdxf',
        'put pbfoouhs',
        'put pkgnyvjd',
        'put awunmlmaf',
        'put xowaenjpcu',
        'put mwxggjjnx',
        'put hyghjgdi',
        'put weopxyzpki',
        'put tztalkspb',
        'put udzsqtdi',
        'del udzsqtdi',
        'del pkgnyvjd',
        'del pbfoouhs',
        'del renrlsby',
        'del tztalkspb',
    ],
    'gone-quiet': [
        'page 32 30',
        'put bacacbab',
        'put bbcccbbc',
        'put bbbbaabbb',
        'put bbcbbaccac',
        'del bbbbaabbb',
    ],
    'gone-right': [
        'page 36 10',
        'put fefaaeba',
        'put dbfaccaf',
        'put eddeeddb',
        'put eccacdfa',
        'del eddeeddb',
        'del eccacdfa',
    ],
    'id-reuse': [
        'page 36 34',
        'put acacaacbba',
        'put aaaababc',
        'put cacabbaa',
        'put cbaabaabb',
        'put ccabbccb',
        'put ccbaccbb',
        'put bbabcabbab',
        'put abaabccbbb',
        'del acacaacbba',
        'put acacaacbba',
    ],
    'join-flat': [
        'page 52 30',
        'put caccceefeb',
        'put bcdedbaf',
        'put ddcfbcfbbd',
        'put fcadefcfe',
        'put cdbaedca',
        'del caccceefeb',
    ],
    'join-left': [
        'page 40 24',
        'put bceeedebd',
        'put bdaecadfee',
        'put baabfbbada',
        'put beefcdbdfa',
        'del bdaecadfee',
    ],
    'join-nomid': [
        'page 32 24',
        'put bbabbbaabc',
        'put babcbcacbb',
        'put ccccaaac',
        'put cbbbaacb',
        'put cabaaccc',
        'put bcccbbcca',
        'put bccccaaca',
        'del bbabbbaabc',
        'del bccccaaca',
    ],
    'join-stuck': [
        'page 40 34',
        'put ccecaffbce',
        'put badcbfeda',
        'put bdfaedecc',
        'del afacafaf',
    ],
    'root-drains': [
        'page 40 14',
        'put aa',
        'put ab',
        'del aa',
        'del ab',
        'put ac',
    ],
    'root-order': [
        'page 32 12',
        'put cccbc',
        'put caccaacc',
        'put bbabcba',
    ],
    'sep-far': [
        'page 44 16',
        'put aaaa',
        'put aaab',
        'put aaac',
        'put aaad',
        'put aaae',
        'put bbbbbbbba',
        'put bbbbbbbbb',
        'put bbbbbbbbc',
        'put bbbbbbbbd',
        'put bbbbbbbbe',
    ],
    'sep-left': [
        'page 32 12',
        'put cccbc',
        'put caccaacc',
        'put bbabcba',
    ],
    'sep-nested': [
        'page 40 14',
        'put mark',
        'put marketaaa',
        'put marketaab',
        'put marketaac',
        'put marketaad',
    ],
    'sep-short': [
        'page 32 12',
        'put cccbc',
        'put caccaacc',
        'put bbabcba',
    ],
    'sep-whole': [
        'page 32 12',
        'put cccbc',
        'put caccaacc',
        'put bbabcba',
    ],
    'size-flat': [
        'page 52 24',
        'put cbabbbabba',
        'put cbcbbcabc',
        'put cccaaaabbb',
        'put cbcbccac',
    ],
    'tower': [
        'page 32 10',
        'put markaa',
        'put markab',
        'put markac',
        'put markad',
        'put markba',
        'put markbb',
        'put markbc',
        'put markbd',
        'put markca',
        'put markcb',
        'put markcc',
        'put markcd',
        'put markda',
        'put markdb',
        'put markdc',
        'put markdd',
    ],
    'twice-missing': [
        'page 40 14',
        'put kite',
        'put kite',
        'del kettle',
        'del kite',
        'del kite',
    ],
}

ORDER = [
    'bound-late',
    'bound-lowonly',
    'bound-never',
    'bound-parent',
    'cap-loose',
    'cut-mid',
    'cut-nopar',
    'cut-sum',
    'cut-tiehigh',
    'fit-ordinary',
    'fit-tips',
    'floor-loose',
    'fold-once',
    'gone-cascade',
    'gone-quiet',
    'gone-right',
    'id-reuse',
    'join-flat',
    'join-left',
    'join-nomid',
    'join-stuck',
    'root-drains',
    'root-order',
    'sep-far',
    'sep-left',
    'sep-nested',
    'sep-short',
    'sep-whole',
    'size-flat',
    'tower',
    'twice-missing',
]


def prog(name):
    return PROGRAMS[name]
